global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "discovery-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8761"]
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: application
        replacement: "discovery-service"

  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: application
        replacement: "api-gateway"

  - job_name: "auth-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8000"]
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: application
        replacement: "auth-service"

  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8060"]
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: application
        replacement: "user-service"

  - job_name: "payment-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8010"]
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: application
        replacement: "payment-service"

  - job_name: "order-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8050"]
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: application
        replacement: "order-service"

  - job_name: "product-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8020"]
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: application
        replacement: "product-service"

  - job_name: "timedeal-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8030"]
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: application
        replacement: "timedeal-service"

  - job_name: "queue-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8040"]
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: application
        replacement: "queue-service"
