# api-gateway
server:
  port: ${API_GATEWAY_PORT:8080}

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6384}
      password: ${REDIS_PASSWORD:}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-routes
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**

            - id: point-routes
              uri: lb://user-service
              predicates:
                - Path=/api/v1/points/**

            - id: auth-routes
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**

            - id: product-routes
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**

            - id: timedeal-routes
              uri: lb://timedeal-service
              predicates:
                - Path=/api/v1/timedeals/**,/api/v1/stocks/**

            - id: order-routes
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**,/api/v1/batch/**

            - id: payment-routes
              uri: lb://payment-service
              predicates:
                - Path=/api/v1/payments/**

            - id: queue-routes
              uri: lb://queue-service
              predicates:
                - Path=/api/v1/queues/**,/api/v1/queue/policies/**,/api/v1/internal/queues/**

          discovery:
            locator:
              enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    expiration: ${JWT_ACCESS_EXPIRED:3600000}
  refresh:
    secret: ${JWT_REFRESH_SECRET}
    expiration: ${JWT_REFRESH_EXPIRED:604800000}

gateway:
  public-paths:
    - /api/v1/auth/signup
    - /api/v1/auth/login
    - /api/v1/timedeals
    - /api/v1/timedeals/search
    - /api/v1/timedeals/search/**
    - /api/v1/timedeals/*
    - /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0
