# queue-service
server:
  port: ${QUEUE_SERVER_PORT:8040}

spring:
  application:
    name: queue-service
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer:
      group-id: queue-service-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${QUEUE_REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        default_schema: queue_schema
        format_sql: true
        use_sql_comments: true
    show-sql: ${SHOW_SQL:false}

logging:
  level:
    org.hibernate.SQL: ${SQL_LOG_LEVEL:INFO}
    org.hibernate.type.descriptor.sql: ${SQL_TYPE_LOG_LEVEL:INFO}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0
