CREATE TABLE notification_schema.p_notification (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    is_read boolean DEFAULT false NOT NULL,
    link character varying(255),
    message character varying(500) NOT NULL,
    title character varying(120) NOT NULL,
    type character varying(32) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT p_notification_type_check CHECK (((type)::text = ANY ((ARRAY['ORDER_CREATED'::character varying, 'ORDER_PAID'::character varying, 'ORDER_CANCELED'::character varying, 'PAYMENT_FAILED'::character varying, 'TIMEDEAL_STARTED'::character varying, 'TIMEDEAL_ENDED'::character varying, 'ACCOUNT_BLOCKED'::character varying, 'ACCOUNT_UNBLOCKED'::character varying, 'ROLE_CHANGED'::character varying])::text[])))
);
ALTER TABLE notification_schema.p_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME notification_schema.p_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY notification_schema.p_notification
    ADD CONSTRAINT p_notification_pkey PRIMARY KEY (id);
CREATE INDEX idx_notification_user_created ON notification_schema.p_notification USING btree (user_id, created_at DESC);
CREATE INDEX idx_notification_user_unread ON notification_schema.p_notification USING btree (user_id, is_read);
