# timedeal-service
server:
  port: ${TIMEDEAL_SERVER_PORT:8030}

spring:
  application:
    name: timedeal-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/rushdeal}
    username: ${DB_USERNAME:rushdeal}
    password: ${DB_PASSWORD:rushdeal}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        default_schema: time_deal_schema
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${TIMEDEAL_REDIS_PORT:6382}
      password: ${REDIS_PASSWORD:}
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
    connection-timeout: 5s
    socket-timeout: 30s
  sql:
    init:
      mode: ${SQL_INIT_MODE:never}
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
  cloud:
    openfeign:
      client:
        config:
          product-service:
            url: ${PRODUCT_SERVICE_URL:http://localhost:8020}

eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}
