package com.rushcrew.notification.domain;

public enum NotificationType {
    ORDER_CREATED,
    ORDER_PAID,
    ORDER_CANCELED,
    PAYMENT_FAILED,
    TIMEDEAL_STARTED,
    TIMEDEAL_ENDING_SOON,
    TIMEDEAL_SOLD_OUT,
    TIMEDEAL_ENDED,
    SELLER_TIMEDEAL_STARTED,
    SELLER_TIMEDEAL_ENDED,
    SELLER_TIMEDEAL_SOLD_OUT,
    ACCOUNT_BLOCKED,
    ACCOUNT_UNBLOCKED,
    ROLE_CHANGED,
}
